# Generated by Django 6.0 on 2025-12-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_recruiter",
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("recruiter", "Recruiter"), ("seeker", "Job Seeker")],
                default="seeker",
                max_length=20,
            ),
        ),
    ]
